### ISSUE TITLE
Track ContactForm7 form submission

### ISSUE THREAD

**Issue by neverything** [wearerequired/openinbound-wordpress#1]
Since ContactForm7 is the most widely used form plugin for WordPress, it makes sense to track it. For now we don't want to create an additional settings screen to map form fields to OpenInbound fields, so we will have to display a help message on the settings screen on what `name` attributes we will track:

* See [CF7 docs for syntax](https://contactform7.com/tag-syntax/)
* Check [example](https://github.com/wearerequired/openinbound-wordpress/blob/ddf96903e01364d3397d24ec6aad6c749653f9f5/classes/Plugin.php#L217-L253) for the use of the [OI API](https://github.com/lukasfischer/openinbound-api) in the main plugin file

**Fields to map:**

**Admin Labels to map:**

* `email`, `E-Mail`
* `name`, `first_name`, `last_name`
* `phone`
* `company_name`

- [x] Use [`FormAbstract`](https://github.com/wearerequired/openinbound-wordpress/blob/master/classes/FormAbstract.php#L11) to implement CF7 tracking using `OI` API
- [ ] Add infos to settings screen on what fields we map.

**Comment by swissspidy** [comment]
After form submission, data is successfully sent to the server. In the dashboard I can see the various page views and the actual submitted form data. The profile is updated as well.

I'm not yet happy with the mapping of the fields (needs a filter). Also, how should the help section look like on the settings screen?

**Comment by neverything** [comment]
- Agree on the filter
- The help text should simply state that in order to track CF7 forms the following name attributes should be used: List of names and link to the CF7 docs on https://contactform7.com/tag-syntax/

Something like this:

### Contact Form 7 and OpenInbound

In order to properly track your contact forms, please use any of the following name attributes when creating form fields: `<list of fields>`.

Please check the Contact Form 7 documentation regarding the [syntax of form fields](https://contactform7.com/tag-syntax/).

**Comment by swissspidy** [comment]
I don't think we need to link to the CF7 syntax. Any user of that plugin should already know that. It's not our job to educate them about another plugin.

**Comment by neverything** [comment]
Agreed let's leave it out and simply tell them the other things.

**Comment by swissspidy** [comment]
Cool, I've done that in badd64ee5ea9e9f74ec77b3cec0aec99f929970a already.

Marking this as fixed.
