### ISSUE TITLE
Track GravityForms form submission

### ISSUE THREAD

**Issue by neverything** [wearerequired/openinbound-wordpress#2]
Since GravityForms is the most widely used **paid** form plugin for WordPress, it makes sense to track it. For now we don't want to create an additional settings screen to map form fields to OpenInbound fields, so we will have to display a help message on the settings screen on how we track the fields:

* See [GF Docs for Admin Labels](https://www.gravityhelp.com/gravity-forms-feature-highlight-admin-labels/)
* Check [example](https://github.com/wearerequired/openinbound-wordpress/blob/ddf96903e01364d3397d24ec6aad6c749653f9f5/classes/Plugin.php#L217-L253) for the use of the [OI API](https://github.com/lukasfischer/openinbound-api) in the main plugin file

**Admin Labels to map:**

* `email`, `E-Mail`
* `name`, `first_name`, `last_name`
* `phone`
* `company_name`

- [ ] Use [`FormAbstract`](https://github.com/wearerequired/openinbound-wordpress/blob/master/classes/FormAbstract.php#L11) to implement GF tracking using `OI` API
- [ ] Add infos to settings screen on how to use the Admin Labels for tracking.

**Comment by swissspidy** [comment]
> For now we don't want to create an additional settings screen to map form fields to OpenInbound fields, so we will have to display a help message on the settings screen on how we track the fields

Sure about that? Gravity Forms has a dedicated `GFFeedAddOn` class one can extend. There you can state the minimum required version of Gravity Forms, needed capabilities, some custom settings, and also a list of fields to map. I have used it before and it's pretty straightforward.

In the admin it would look like this:

<img width="556" alt="screen shot 2017-05-02 at 17 58 55" src="https://cloud.githubusercontent.com/assets/841956/25626904/4153ac40-2f61-11e7-9dc6-e2e75f996dcc.png">

<img width="653" alt="screen shot 2017-05-02 at 17 59 59" src="https://cloud.githubusercontent.com/assets/841956/25626914/4780c6ac-2f61-11e7-9900-5b2fc8862d52.png">

**Comment by neverything** [comment]
Didn't know about this and makes thing approx. 100x easier for the user. How much time do you estimate it would take to do this compared to the other solution proposed above?

**Comment by swissspidy** [comment]
Agreed. The usability improvement will save plenty of time later on with support etc as well.

Given that `GFFeedAddOn` offers pretty much all of the features needed here, we don't have to worry about edge cases when trying to force everything into `FormInterface` / `FormAbstract`. I'd say it's more in the 1-2h spectrum instead of a 3-4h one for a custom solution.

**Comment by neverything** [comment]
Excellent, please go ahead implementing it with `GFFeedAddOn`.

**Comment by swissspidy** [comment]
With the current configuration it like this:

<img width="861" alt="screen shot 2017-05-03 at 18 37 51" src="https://cloud.githubusercontent.com/assets/841956/25671285/ac7bc1d2-302f-11e7-918b-5cf47d235b54.png">

We can easily remove the 'Custom Fields' and 'Opt-In Condition' sections if not needed. Also, we can prevent having multiple feeds configured.

Right now one can send different data based on different conditions. Not sure how much sense that makes though.

**Comment by swissspidy** [comment]
After form submission, data is successfully sent to the server. In the dashboard I can see the various page views and the actual submitted form data. The profile is updated as well.

We can consider this integration being done. The only open question in my eyes is this:

> We can easily remove the 'Custom Fields' and 'Opt-In Condition' sections if not needed. Also, we can prevent having multiple feeds configured.
> 
> Right now one can send different data based on different conditions. Not sure how much sense that makes though.

**Comment by neverything** [comment]
I'd say we can omit the custom fields for now. With multiple feeds you mean tracking different forms (that would be nice to have)? Tracking the same form multiple times is not necessary.

**Comment by swissspidy** [comment]
With multiple feeds I mean multiple feeds _per form_, e.g. based on different conditions. For example, with a newsletter feed you'd want to subscribe a user for a list A when they select one option, and for list B when they select another. That means you need two feeds.

Tracking different forms is status quo, because that feed setting you see is _per form_.

**Comment by neverything** [comment]
Excellent so we can omit the multiple feeds based on conditions.
