### ISSUE TITLE
Prepare plugin for w.org submission

### ISSUE THREAD

**Issue by neverything** [wearerequired/openinbound-wordpress#4]
- [x] Add contributors `wearerequired`, `openinbound`
- [x] Ask @lukasfischer for a proper description
- [x] Ask @lukasfischer for proper assets (image, icon)
- [x] Prepare `README.md`
- [x] Let @lukasfischer review the plugin and maybe make a video of how the tracking goes into our OpenInbound account (see 1pass for login and API keys)
- [x] Submit the plugin to w.org

**Comment by swissspidy** [comment]
Note: Although the plugin directory supports Markdown and `README.md` files, they recommend using a separate `readme.txt` file: https://make.wordpress.org/plugins/2017/04/05/reminder-how-svn-wordpress-org-works/

**Comment by swissspidy** [comment]
More info on the readme: https://wordpress.org/plugins/developers/
Example readme: https://wordpress.org/plugins/files/2016/06/readme.txt
Readme validator: https://wordpress.org/plugins/developers/readme-validator/

**Comment by neverything** [comment]
@swissspidy ahh didn't know. So we should generate a readme.txt from a README.md or do it by hand?

**Comment by swissspidy** [comment]
@neverything For now I added a separate readme.txt file for the plugin directory.

A README.md is still useful for developer info like on how to contribute etc. No need to have them in sync.

**Comment by swissspidy** [comment]
@lukasfischer I just added the build tasks we were talking about and updated the readme so you can see how it works. Here's the current plugin, ready for submission:

[openinbound.zip](https://github.com/wearerequired/openinbound-wordpress/files/1055817/openinbound.zip)

Note: you should use the slug "openinbound" when submitting the plugin, not "openinbound-wordpress".
